apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-bkgrp06-1
  namespace: bkgrp06-1
  labels:
    type: local
spec:
  storageClassName: document
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db/bkgrp06-1"